#!/bin/sh
set -e

# X tries to install quite a bit in /etc/X11. The root filesystem is not
# big enough for this. Create /usr/X11R6/etc and a symbolic link from
# /etc/X11 to this directory.
mkdir /usr/X11R6
mkdir /usr/X11R6/etc

if [ -f /usr/gnu/bin/gcc ]
then
	# Build X libraries compiled with gcc
	sh build.gccdevel
fi

if [ -d /etc/X11 ]; then echo '/etc/X11' exists 2>&1; exit 1; fi
ln -s /usr/X11R6/etc /etc/X11
cd xc
make World
make install
make install.man

# Make everything bin-owned except for suid files. (And symlinks,
# which point to suid files.)
echo "Changing owner to bin"
find /usr/X11R6 /usr/X11R6-gcc ! -perm -4000 -a \( -type f -o -type d \) | xargs -n 10 chown bin
